version: "3.5"
services:
  agent:
    restart: unless-stopped
    build: .
    ports:
      - "80:8080"
    environment:
      TH1_PIN: "2"
      TH2_PIN: "10"
      OC1_PIN: "15"
      OC2_PIN: "18"
      OC3_PIN: "14"
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    cap_add:
      - SYS_RAWIO
    privileged: true
    healthcheck:
      test: ["CMD-SHELL", "wget localhost:8080 -O - -q -T 15 || kill 1"]
      interval: 30m
      timeout: 30s
      retries: 1
      start_period: 30m
